services:
  - type: web
    name: movie-reviews-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DB
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GA_KEY
        sync: false
    healthCheckPath: /movies
    autoDeploy: true
    plan: free 